node {
    customWorkspace 'C:\Users\Ivan\Documents\bluebank'

    withMaven(maven:'maven') {

        stage('Build') {
            dir ('Servidor-Eureka') {
                bat 'mvn clean install -DskipTests'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version   
            }
        }

        stage('Image') {
            dir ('Servidor-Eureka') {
                def app = docker.build "localhost:5000/discovery-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'cliente-conta-service-pipeline', wait: false
        }      

    }

}