node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ivancmc/bluebank.git', credentialsId: 'ivancmc', branch: 'develop'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('cliente-conta-service') {
                def app = docker.build "localhost:5000/cliente-conta-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/cliente-conta-service:${env.version}").run('-p 8101:8101 -h cliente-conta --name cliente-conta --link db --link discovery')
        }

        stage ('Final') {
            build job: 'transacoes-service-pipeline', wait: false
        }      

    }

}