node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ivancmc/bluebank.git', credentialsId: 'ivancmc', branch: 'develop'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('transacoes-service') {
                def app = docker.build "localhost:5000/transacoes-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/transacoes-service:${env.version}").run('-p 8102:8102 -h transacoes --name transacoes --link db --link discovery --link cliente-conta')
        }
    }

}